In [3]:
import pandas as pd
from sqlalchemy import create_engine
import numpy as np

#  Step 1: Extract and read source data (CSVs)

In [4]:
approval_load = "./Sources/Approval_list.csv"
header_load = "./Sources/Order_header_list.csv"
line_load = "./Sources/Order_line_list.csv"
star_load = "./Sources/STARS_classification_2020.csv"
rate_load = "./Sources/Ex_rate_2019.csv"

approval_data = pd.read_csv(approval_load)
header_data = pd.read_csv(header_load)
line_data = pd.read_csv(line_load)
star_data = pd.read_csv(star_load)
rate_data = pd.read_csv(rate_load)

# print(rate_data.columns.values)
# print(star_data.columns.values)
# print(header_data.columns.values)
# print(approval_data.columns.values)
# print(line_data.columns.values)

# Step 2: Create tables in PostgreSQL (SQL tables schema)

# Step 3: Transform, clean,  & format data in Pandas
## (5 dataframes in total)

### 1) Currency exchange rate data

In [143]:
#Rename columns and change positions
currency = rate_data["Currency"]
concatenate = rate_data["concatenate"]
exchange_rate = round(rate_data["ex rate to use 2019"],6)

rate_df = rate_data.rename(columns={"Currency": "currency", "concatenate": "exchange_code", "ex rate to use 2019": "exchange_rate_to_eur"})
rate_df.head()

  currency exchange_code  exchange_rate_to_eur
0      EUR       EUR2019              1.000000
1      AED       AED2019              0.242220
2      AOA       AOA2019              0.002626
3      ARS       ARS2019              0.017691
4      AUD       AUD2019              0.617868

##### Export to PorstgreSQL

In [36]:
#create engine & connection
rds_connection_string = "postgres:5erverlab@localhost:5432/DataAnalyticsBootcamp-Project2"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [5]:
engine.table_names()

['star_data', 'exchange_rates', 'order_header', 'approval_data', 'order_line']

['star_data', 'exchange_rates', 'order_header', 'approval_data', 'order_line']

In [ ]:
#export to Postgres
rate_df.to_sql(name='exchange_rates', con=engine, if_exists='append', index=False)

### 2) Technical information ("STAR") data

In [5]:
star_data.head()

,Market/ Marché,Category / Categorie,Technological Group / Regroupement Technologique,Family / Famille
0,SE,NaN,NaN,NaN
1,SE,E2,NaN,NaN
2,SE,E2,E2,NaN
3,SE,E2,E2,14A
4,SE,E2,E2,14B

In [6]:
#Rename columns
star_df = star_data.rename(columns={"Family / Famille": "star_family", "Market/ Marché": "market", "Category / Categorie": "category", "Technological Group / Regroupement Technologique": "technology"})
star_df = star_df[["star_family", "market", "category", "technology"]]

star_df.head()

  star_family market category technology
0         NaN     SE      NaN        NaN
1         NaN     SE       E2        NaN
2         NaN     SE       E2         E2
3         14A     SE       E2         E2
4         14B     SE       E2         E2

In [7]:
#drop unecessary null values
star_df.count()

star_family    168
market         251
category       250
technology     229
dtype: int64

In [8]:
star_df = star_df[star_df['star_family'].notnull()] 
star_df.head()

  star_family market category technology
3         14A     SE       E2         E2
4         14B     SE       E2         E2
5         14C     SE       E2         E2
6         14D     SE       E2         E2
7         14I     SE       E2         E2

In [9]:
star_df.count()

star_family    168
market         168
category       168
technology     168
dtype: int64

In [10]:
star_df.head()

  star_family market category technology
3         14A     SE       E2         E2
4         14B     SE       E2         E2
5         14C     SE       E2         E2
6         14D     SE       E2         E2
7         14I     SE       E2         E2

In [ ]:
#export to PostGresSQL
star_df.to_sql(name='star_data', con=engine, if_exists='append', index=False)

### 3) Order data by Purchase Order Header

In [11]:
header_data.head()

,Req,PO Number,Order Date,Status,Transmission Status,Unanswered Comments,Items,Total,Currency
0,25586,8000016091,02/27/20,Issued,Sent via Email,False,1 Each of MUVIT SUPPORT UNIVERSEL NOIR ROTATIF...,66.79,EUR
1,23295,8000016090,02/27/20,Issued,Sent via Email,False,1 Each of (ST)Stylo bille Bic 4 couleurs 3 + 1...,51.90,EUR
2,25352,8000016089,02/27/20,Issued,Sent via Email,False,"1 Each of Cotisation 2020 RESEAU ALLIANCES,1 E...",570.00,EUR
3,25189,8000016088,02/27/20,Issued,Sent via Email,False,1 Each of REGUL FACT ESCALE REPAS FORMATION 0...,906.47,EUR
4,15750,8000016087,02/27/20,Issued,Sent via Email,False,"1 Each of intégration caméra et marquage T-3,1...",730.00,EUR

In [12]:
#Drop unecessary columns
header_data = header_data.drop(columns=['Items', 'Total','Currency','Unanswered Comments'])
header_data.head()

     Req   PO Number Order Date  Status Transmission Status
0  25586  8000016091   02/27/20  Issued      Sent via Email
1  23295  8000016090   02/27/20  Issued      Sent via Email
2  25352  8000016089   02/27/20  Issued      Sent via Email
3  25189  8000016088   02/27/20  Issued      Sent via Email
4  15750  8000016087   02/27/20  Issued      Sent via Email

In [13]:
#Renaming columns
header_df = header_data.rename(columns={"Req":"requisition_number", "PO Number": "po_number", "Order Date": "order_date", "Status": "status", "Transmission Status":"transmission_method"})
header_df = header_df[["po_number", "requisition_number", "order_date", "status", "transmission_method"]] 
header_df.head()

    po_number  requisition_number order_date  status transmission_method
0  8000016091               25586   02/27/20  Issued      Sent via Email
1  8000016090               23295   02/27/20  Issued      Sent via Email
2  8000016089               25352   02/27/20  Issued      Sent via Email
3  8000016088               25189   02/27/20  Issued      Sent via Email
4  8000016087               15750   02/27/20  Issued      Sent via Email

In [14]:
#Dropping Duplicates
header_df.drop_duplicates("requisition_number", inplace=True)
header_df.head()

    po_number  requisition_number order_date  status transmission_method
0  8000016091               25586   02/27/20  Issued      Sent via Email
1  8000016090               23295   02/27/20  Issued      Sent via Email
2  8000016089               25352   02/27/20  Issued      Sent via Email
3  8000016088               25189   02/27/20  Issued      Sent via Email
4  8000016087               15750   02/27/20  Issued      Sent via Email

In [15]:
#double checking variable types to sync with PostGres
header_df.dtypes

po_number               int64
requisition_number      int64
order_date             object
status                 object
transmission_method    object
dtype: object

In [ ]:
#Export to Postgres
header_df.to_sql(name='order_header', con=engine, if_exists='append', index=False)

### 4) Date for Approval of Purchases

In [16]:
approval_data.head()

,Document Number,Document,Document Total,Approver,Delegates,Approval Limit,Submission Date (UTC),First Notification (UTC),Approval Date (UTC),Local Approval Date,Approval Duration,Status,Note,Position,Type,Approval Chain,Override,Reasons,Skip Escalation
0,9,Requisition #9,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False
1,11,Requisition #11,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False
2,12,Requisition #12,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False
3,14,Requisition #14,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False
4,15,Requisition #15,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False

In [17]:
#Drop unecessary columns
approval_df = approval_data.drop(columns=['Document'])
approval_df.head()

,Document Number,Document Total,Approver,Delegates,Approval Limit,Submission Date (UTC),First Notification (UTC),Approval Date (UTC),Local Approval Date,Approval Duration,Status,Note,Position,Type,Approval Chain,Override,Reasons,Skip Escalation
0,9,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False
1,11,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False
2,12,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False
3,14,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False
4,15,0.0,IC&D Pacy,None,NaN,NaN,NaN,NaN,NaN,NaN,pending_approval,NaN,1,UltimateApproverApproval,0,0,The requester has no manager defined.,False

In [19]:
#Checking counts before dropping null values & drop null values
approval_df.count()

Document Number             62141
Document Total              62141
Approver                    62141
Delegates                   62141
Approval Limit              28106
Submission Date (UTC)       61094
First Notification (UTC)    35235
Approval Date (UTC)         57475
Local Approval Date         57475
Approval Duration           34480
Status                      62141
Note                         2320
Position                    62141
Type                        62141
Approval Chain              62141
Override                    62141
Reasons                     60584
Skip Escalation             62141
dtype: int64

In [20]:
approval_df_modified = approval_df[approval_df['Approval Duration'].notnull()] 
approval_df_modified.head()

,Document Number,Document Total,Approver,Delegates,Approval Limit,Submission Date (UTC),First Notification (UTC),Approval Date (UTC),Local Approval Date,Approval Duration,Status,Note,Position,Type,Approval Chain,Override,Reasons,Skip Escalation
14,47,9.36,Digital Procurement Operations,None,"30,000.00",05/24/19 09:37 AM,05/24/19 09:37 AM,05/24/19 09:45 AM,05/24/19 11:45 AM,0 - 00:07:49,approved,Smoke test Dummy PR,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
15,53,13.05,Digital Procurement Operations,None,"30,000.00",05/24/19 10:44 AM,05/24/19 10:45 AM,05/24/19 10:46 AM,05/24/19 12:46 PM,0 - 00:01:11,approved,Smoke Test - Dummy PR,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
16,1,16.84,Digital Procurement Operations,None,"100,000,000,000.00",05/24/19 11:57 AM,05/24/19 11:58 AM,05/24/19 12:01 PM,05/24/19 02:01 PM,0 - 00:03:02,approved,NaN,1,ApprovalChainApproval,138,0,Added by the approval chain PO Change - Digita...,False
17,2,8.28,Digital Procurement Operations,None,"100,000,000,000.00",05/24/19 12:05 PM,05/24/19 12:05 PM,05/24/19 12:09 PM,05/24/19 02:09 PM,0 - 00:03:10,approved,NaN,1,ApprovalChainApproval,138,0,Added by the approval chain PO Change - Digita...,False
18,55,125000.00,Digital Procurement Operations,None,"30,000.00",06/04/19 12:30 PM,06/04/19 01:45 PM,06/04/19 01:49 PM,06/04/19 03:49 PM,0 - 00:03:48,approved,NaN,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False

In [21]:
# Cehcking counts after dropping null values
approval_df_modified.dtypes

Document Number               int64
Document Total              float64
Approver                     object
Delegates                    object
Approval Limit               object
Submission Date (UTC)        object
First Notification (UTC)     object
Approval Date (UTC)          object
Local Approval Date          object
Approval Duration            object
Status                       object
Note                         object
Position                      int64
Type                         object
Approval Chain                int64
Override                      int64
Reasons                      object
Skip Escalation                bool
dtype: object

In [22]:
#Changing variable types for Datetime columns

approval_df_modified['Submission Date (UTC)'] = pd.to_datetime(approval_df_modified['Submission Date (UTC)'])
approval_df_modified['First Notification (UTC)'] = pd.to_datetime(approval_df_modified['First Notification (UTC)'])
approval_df_modified['Approval Date (UTC)'] = pd.to_datetime(approval_df_modified['Approval Date (UTC)'])
approval_df_modified['Local Approval Date'] = pd.to_datetime(approval_df_modified['Local Approval Date'])

C:\Users\Purvi Patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Purvi Patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Purvi Patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Purvi Patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [23]:
#checking datetime formatting
approval_df_modified.head()

,Document Number,Document Total,Approver,Delegates,Approval Limit,Submission Date (UTC),First Notification (UTC),Approval Date (UTC),Local Approval Date,Approval Duration,Status,Note,Position,Type,Approval Chain,Override,Reasons,Skip Escalation
14,47,9.36,Digital Procurement Operations,None,"30,000.00",2019-05-24 09:37:00,2019-05-24 09:37:00,2019-05-24 09:45:00,2019-05-24 11:45:00,0 - 00:07:49,approved,Smoke test Dummy PR,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
15,53,13.05,Digital Procurement Operations,None,"30,000.00",2019-05-24 10:44:00,2019-05-24 10:45:00,2019-05-24 10:46:00,2019-05-24 12:46:00,0 - 00:01:11,approved,Smoke Test - Dummy PR,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
16,1,16.84,Digital Procurement Operations,None,"100,000,000,000.00",2019-05-24 11:57:00,2019-05-24 11:58:00,2019-05-24 12:01:00,2019-05-24 14:01:00,0 - 00:03:02,approved,NaN,1,ApprovalChainApproval,138,0,Added by the approval chain PO Change - Digita...,False
17,2,8.28,Digital Procurement Operations,None,"100,000,000,000.00",2019-05-24 12:05:00,2019-05-24 12:05:00,2019-05-24 12:09:00,2019-05-24 14:09:00,0 - 00:03:10,approved,NaN,1,ApprovalChainApproval,138,0,Added by the approval chain PO Change - Digita...,False
18,55,125000.00,Digital Procurement Operations,None,"30,000.00",2019-06-04 12:30:00,2019-06-04 13:45:00,2019-06-04 13:49:00,2019-06-04 15:49:00,0 - 00:03:48,approved,NaN,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False

In [24]:
# Turning datatime values into strings in order to export to PostGres

approval_df_modified['Submission Date (UTC)'] = approval_df_modified['Submission Date (UTC)'].astype(str)

approval_df_modified['First Notification (UTC)'] = approval_df_modified['First Notification (UTC)'].astype(str)

approval_df_modified['Approval Date (UTC)'] = approval_df_modified['Approval Date (UTC)'].astype(str)

approval_df_modified['Local Approval Date'] = approval_df_modified['Local Approval Date'].astype(str)

C:\Users\Purvi Patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Purvi Patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Purvi Patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Purvi Patel\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [25]:
#Renaming all columns to make it "Postgres friendly"

approval_df_modified=approval_df_modified.rename(columns={'Approver':'approver','Delegates':'delegates',
       'Document Number': 'document_number', 'Document Total': 'document_total',
       'Approval Limit': 'approval_limit', 'Submission Date (UTC)': 'submission_date',
       'First Notification (UTC)': 'first_notification', 'Approval Date (UTC)': 'approval_date',
       'Local Approval Date': 'local_approval_date', 'Approval Duration': 'approval_duration', 'Status': 'status', 'Note': 'note',
       'Position': 'position', 'Type': 'type', 'Approval Chain': 'approval_chain', 'Override': 'override', 'Reasons': 'reasons',
       'Skip Escalation': 'skip_escalation'})

In [26]:
approval_df_modified

,document_number,document_total,approver,delegates,approval_limit,submission_date,first_notification,approval_date,local_approval_date,approval_duration,status,note,position,type,approval_chain,override,reasons,skip_escalation
14,47,9.36,Digital Procurement Operations,None,"30,000.00",2019-05-24 09:37:00,2019-05-24 09:37:00,2019-05-24 09:45:00,2019-05-24 11:45:00,0 - 00:07:49,approved,Smoke test Dummy PR,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
15,53,13.05,Digital Procurement Operations,None,"30,000.00",2019-05-24 10:44:00,2019-05-24 10:45:00,2019-05-24 10:46:00,2019-05-24 12:46:00,0 - 00:01:11,approved,Smoke Test - Dummy PR,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
16,1,16.84,Digital Procurement Operations,None,"100,000,000,000.00",2019-05-24 11:57:00,2019-05-24 11:58:00,2019-05-24 12:01:00,2019-05-24 14:01:00,0 - 00:03:02,approved,NaN,1,ApprovalChainApproval,138,0,Added by the approval chain PO Change - Digita...,False
17,2,8.28,Digital Procurement Operations,None,"100,000,000,000.00",2019-05-24 12:05:00,2019-05-24 12:05:00,2019-05-24 12:09:00,2019-05-24 14:09:00,0 - 00:03:10,approved,NaN,1,ApprovalChainApproval,138,0,Added by the approval chain PO Change - Digita...,False
18,55,125000.00,Digital Procurement Operations,None,"30,000.00",2019-06-04 12:30:00,2019-06-04 13:45:00,2019-06-04 13:49:00,2019-06-04 15:49:00,0 - 00:03:48,approved,NaN,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62065,1434,72500.00,Zeng Huang,None,"50,000.00",2020-02-27 12:23:00,2020-02-27 16:55:00,2020-02-27 17:38:00,2020-02-27 18:38:00,0 - 00:43:05,approved,NaN,3,ApprovalChainApproval,177,0,Added by the approval chain PO Change - Schnei...,False
62085,25586,66.79,Ivan Llaurado,None,"10,000.00",2020-02-27 17:17:00,2020-02-27 17:17:00,2020-02-27 18:53:00,2020-02-27 19:53:00,0 - 01:35:47,approved,NaN,1,ApprovalChainApproval,157,0,Added by the approval chain Requisition - Schn...,False
62086,23295,51.90,Ivan Llaurado,None,"10,000.00",2020-02-27 17:17:00,2020-02-27 17:18:00,2020-02-27 18:53:00,2020-02-27 19:53:00,0 - 01:35:20,approved,NaN,1,ApprovalChainApproval,157,0,Added by the approval chain Requisition - Schn...,False
62103,12213,3315.00,Jean-Francois Carvalho,None,"50,000.00",2020-02-26 09:55:00,2020-02-27 17:37:00,2020-02-27 17:41:00,2020-02-27 18:41:00,0 - 00:04:17,approved,NaN,3,ApprovalChainApproval,157,0,Added by the approval chain Requisition - Schn...,False
62106,24595,238.60,Regis Briot,None,"10,000.00",2020-02-21 10:15:00,2020-02-27 17:40:00,2020-02-27 17:41:00,2020-02-27 18:41:00,0 - 00:01:13,approved,NaN,3,ApprovalChainApproval,157,0,Added by the approval chain Requisition - Schn...,False

,document_number,document_total,approver,delegates,approval_limit,submission_date,first_notification,approval_date,local_approval_date,approval_duration,status,note,position,type,approval_chain,override,reasons,skip_escalation
14,47,9.36,Digital Procurement Operations,None,"30,000.00",2019-05-24 09:37:00,2019-05-24 09:37:00,2019-05-24 09:45:00,2019-05-24 11:45:00,0 - 00:07:49,approved,Smoke test Dummy PR,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
15,53,13.05,Digital Procurement Operations,None,"30,000.00",2019-05-24 10:44:00,2019-05-24 10:45:00,2019-05-24 10:46:00,2019-05-24 12:46:00,0 - 00:01:11,approved,Smoke Test - Dummy PR,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
16,1,16.84,Digital Procurement Operations,None,"100,000,000,000.00",2019-05-24 11:57:00,2019-05-24 11:58:00,2019-05-24 12:01:00,2019-05-24 14:01:00,0 - 00:03:02,approved,NaN,1,ApprovalChainApproval,138,0,Added by the approval chain PO Change - Digita...,False
17,2,8.28,Digital Procurement Operations,None,"100,000,000,000.00",2019-05-24 12:05:00,2019-05-24 12:05:00,2019-05-24 12:09:00,2019-05-24 14:09:00,0 - 00:03:10,approved,NaN,1,ApprovalChainApproval,138,0,Added by the approval chain PO Change - Digita...,False
18,55,125000.00,Digital Procurement Operations,None,"30,000.00",2019-06-04 12:30:00,2019-06-04 13:45:00,2019-06-04 13:49:00,2019-06-04 15:49:00,0 - 00:03:48,approved,NaN,1,ApprovalChainApproval,132,0,Added by the approval chain Non-Catalog Requis...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62065,1434,72500.00,Zeng Huang,None,"50,000.00",2020-02-27 12:23:00,2020-02-27 16:55:00,2020-02-27 17:38:00,2020-02-27 18:38:00,0 - 00:43:05,approved,NaN,3,ApprovalChainApproval,177,0,Added by the approval chain PO Change - Schnei...,False
62085,25586,66.79,Ivan Llaurado,None,"10,000.00",2020-02-27 17:17:00,2020-02-27 17:17:00,2020-02-27 18:53:00,2020-02-27 19:53:00,0 - 01:35:47,approved,NaN,1,ApprovalChainApproval,157,0,Added by the approval chain Requisition - Schn...,False
62086,23295,51.90,Ivan Llaurado,None,"10,000.00",2020-02-27 17:17:00,2020-02-27 17:18:00,2020-02-27 18:53:00,2020-02-27 19:53:00,0 - 01:35:20,approved,NaN,1,ApprovalChainApproval,157,0,Added by the approval chain Requisition - Schn...,False
62103,12213,3315.00,Jean-Francois Carvalho,None,"50,000.00",2020-02-26 09:55:00,2020-02-27 17:37:00,2020-02-27 17:41:00,2020-02-27 18:41:00,0 - 00:04:17,approved,NaN,3,ApprovalChainApproval,157,0,Added by the approval chain Requisition - Schn...,False
62106,24595,238.60,Regis Briot,None,"10,000.00",2020-02-21 10:15:00,2020-02-27 17:40:00,2020-02-27 17:41:00,2020-02-27 18:41:00,0 - 00:01:13,approved,NaN,3,ApprovalChainApproval,157,0,Added by the approval chain Requisition - Schn...,False

In [ ]:
#Exporting to PostGres

approval_df_modified.to_sql(name='approval_data', con=engine, if_exists='append', index=False)

### 5) Purchase order data by line item

In [27]:
line_data.head()

,Line,PO Number (Header),Order Status (Header),Order Transmission Status (Header),Item,Line Total,Currency,Account,Chart Of Accounts,Contract Number,ERP,Item Classification,Accounting Total Currency,po_key
0,1,8000016091,Issued,Sent via Email,MUVIT SUPPORT UNIVERSEL NOIR ROTATIF GRI,5.49,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8000016091-1
1,2,8000016091,Issued,Sent via Email,Targus DrifterTrek with USB Power Pass-T,53.30,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8000016091-2
2,3,8000016091,Issued,Sent via Email,FRAIS DE PORT,8.00,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8000016091-3
3,1,8000016090,Issued,Sent via Email,(ST)Stylo bille Bic 4 couleurs 3 + 1 HB - poin...,2.84,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR,8000016090-1
4,2,8000016090,Issued,Sent via Email,(ST)Pile bouton lithium Energizer CR2025 - pac...,5.39,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR,8000016090-2

In [28]:
#Create new column with PO number and order line item number, to have as primary key in PostGres

line_data['po_key']=line_data['PO Number (Header)'].astype(str)+'-'+ line_data['Line'].astype(str)
line_data.head()

,Line,PO Number (Header),Order Status (Header),Order Transmission Status (Header),Item,Line Total,Currency,Account,Chart Of Accounts,Contract Number,ERP,Item Classification,Accounting Total Currency,po_key
0,1,8000016091,Issued,Sent via Email,MUVIT SUPPORT UNIVERSEL NOIR ROTATIF GRI,5.49,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8000016091-1
1,2,8000016091,Issued,Sent via Email,Targus DrifterTrek with USB Power Pass-T,53.30,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8000016091-2
2,3,8000016091,Issued,Sent via Email,FRAIS DE PORT,8.00,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8000016091-3
3,1,8000016090,Issued,Sent via Email,(ST)Stylo bille Bic 4 couleurs 3 + 1 HB - poin...,2.84,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR,8000016090-1
4,2,8000016090,Issued,Sent via Email,(ST)Pile bouton lithium Energizer CR2025 - pac...,5.39,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR,8000016090-2

In [29]:
#Rename and reorder columns in dataframe

line_df = line_data.rename(columns={"Line":"line", "PO Number (Header)":"po_number", "Order Status (Header)": "order_status", "Order Transmission Status (Header)": "transmission_method",
                                   "Item": "item", "Line Total": "line_total", "Currency": "currency", "Account": "account", "Chart Of Accounts": "chart_of_accounts", "Contract Number": "contract_number", "ERP": "erp", "Item Classification": "item_classification", "Accounting Total Currency": "accounting_total_currency"})
line_df = line_df[["po_key", "po_number", "line", "order_status", "transmission_method", "item", "line_total", "currency", "account", "chart_of_accounts", "contract_number", "erp", "item_classification", "accounting_total_currency"]] 
line_df.head()

,po_key,po_number,line,order_status,transmission_method,item,line_total,currency,account,chart_of_accounts,contract_number,erp,item_classification,accounting_total_currency
0,8000016091-1,8000016091,1,Issued,Sent via Email,MUVIT SUPPORT UNIVERSEL NOIR ROTATIF GRI,5.49,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
1,8000016091-2,8000016091,2,Issued,Sent via Email,Targus DrifterTrek with USB Power Pass-T,53.30,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
2,8000016091-3,8000016091,3,Issued,Sent via Email,FRAIS DE PORT,8.00,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
3,8000016090-1,8000016090,1,Issued,Sent via Email,(ST)Stylo bille Bic 4 couleurs 3 + 1 HB - poin...,2.84,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR
4,8000016090-2,8000016090,2,Issued,Sent via Email,(ST)Pile bouton lithium Energizer CR2025 - pac...,5.39,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR

In [ ]:
#Exporting to PostGres

line_df.to_sql(name='old_order_line', con=engine, if_exists='append', index=False)

# Step 4: Analysis in PostGres (run SQL join, export join, reload into Pandas)

In [30]:
#Run JOIN in SQL
#Copy (SELECT * FROM order_line
#LEFT JOIN order_header
#ON order_line.po_number = order_header.po_number)
#To 'C:\Users\[UserName]\Documents\GitHub\etl_project\ETL Project\SourcesJoins.csv' With CSV DELIMITER ',' HEADER;

#Load exported data back in Pandas for cleaning
join_tables = "./Sources/Join777.csv"

In [31]:
join_tables = pd.read_csv(join_tables)

join_tables

,po_key,po_number,line,order_status,transmission_method,item,line_total,currency,account,chart_of_accounts,contract_number,erp,item_classification,accounting_total_currency,po_number.1,requisition_number,order_date,status,transmission_method.1
0,8000016091-1,8000016091,1,Issued,Sent via Email,MUVIT SUPPORT UNIVERSEL NOIR ROTATIF GRI,5.49,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8000016091,25586,02/27/20,Issued,Sent via Email
1,8000016091-2,8000016091,2,Issued,Sent via Email,Targus DrifterTrek with USB Power Pass-T,53.30,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8000016091,25586,02/27/20,Issued,Sent via Email
2,8000016091-3,8000016091,3,Issued,Sent via Email,FRAIS DE PORT,8.00,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8000016091,25586,02/27/20,Issued,Sent via Email
3,8000016090-1,8000016090,1,Issued,Sent via Email,(ST)Stylo bille Bic 4 couleurs 3 + 1 HB - poin...,2.84,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR,8000016090,23295,02/27/20,Issued,Sent via Email
4,8000016090-2,8000016090,2,Issued,Sent via Email,(ST)Pile bouton lithium Energizer CR2025 - pac...,5.39,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR,8000016090,23295,02/27/20,Issued,Sent via Email
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39822,8300000005-1,8300000005,1,Issued,Sent via Email,Logz.IO subscription - Integration IFW platform,26165.29,EUR,FREN-K - 53323---PL - FREN - K323,SEI SAS (FREN),NaN,BEU,Software As A Service (Saas) Subscriptions ---...,EUR,8300000005,112,06/06/19,Issued,Sent via Email
39823,8200000004-1,8200000004,1,Issued,Sent via Email,Oracle Hyperion Financial Data Quality Managem...,62848.50,USD,US01-K - US012774---PL - US01 - US76--,SE US (US01),NaN,BAM,Software Licenses Procurement --- It Softw Mai...,USD,8200000004,82,06/06/19,Issued,Sent via Email
39824,8200000004-2,8200000004,2,Issued,Sent via Email,Oracle Hyperion Financial Data Quality Managem...,13003.50,USD,US01-K - US012774---PL - US01 - US76--,SE US (US01),NaN,BAM,Software Licenses Procurement --- It Softw Mai...,USD,8200000004,82,06/06/19,Issued,Sent via Email
39825,8300000003-1,8300000003,1,Issued,Sent via Email,Coupa 6 months 5000 users subscription renewal,125000.00,EUR,FREN-K - 53997-P - SP-AUTO-PG1039-PL - FREN - ...,SEI SAS (FREN),NaN,BEU,Software As A Service (Saas) Subscriptions ---...,EUR,8300000003,55,06/04/19,Issued,Sent via Email
39826,8300000002-1,8300000002,1,Cancelled,Sent via Email,Smoke Test - Dummy PR,16.84,EUR,FREN-K - 53376---PL - FREN - K323,SEI SAS (FREN),NaN,BEU,Computer Peripherals / Photocopiers --- Office...,EUR,8300000002,53,05/24/19,Cancelled,Sent via Email

In [32]:
#Drop excess columns & resave to create 6th table in Postgres
join_tables = join_tables.drop(columns=['requisition_number', "order_date", 'status', 'transmission_method.1', "po_number.1"])

In [33]:
join_tables

,po_key,po_number,line,order_status,transmission_method,item,line_total,currency,account,chart_of_accounts,contract_number,erp,item_classification,accounting_total_currency
0,8000016091-1,8000016091,1,Issued,Sent via Email,MUVIT SUPPORT UNIVERSEL NOIR ROTATIF GRI,5.49,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
1,8000016091-2,8000016091,2,Issued,Sent via Email,Targus DrifterTrek with USB Power Pass-T,53.30,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
2,8000016091-3,8000016091,3,Issued,Sent via Email,FRAIS DE PORT,8.00,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
3,8000016090-1,8000016090,1,Issued,Sent via Email,(ST)Stylo bille Bic 4 couleurs 3 + 1 HB - poin...,2.84,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR
4,8000016090-2,8000016090,2,Issued,Sent via Email,(ST)Pile bouton lithium Energizer CR2025 - pac...,5.39,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39822,8300000005-1,8300000005,1,Issued,Sent via Email,Logz.IO subscription - Integration IFW platform,26165.29,EUR,FREN-K - 53323---PL - FREN - K323,SEI SAS (FREN),NaN,BEU,Software As A Service (Saas) Subscriptions ---...,EUR
39823,8200000004-1,8200000004,1,Issued,Sent via Email,Oracle Hyperion Financial Data Quality Managem...,62848.50,USD,US01-K - US012774---PL - US01 - US76--,SE US (US01),NaN,BAM,Software Licenses Procurement --- It Softw Mai...,USD
39824,8200000004-2,8200000004,2,Issued,Sent via Email,Oracle Hyperion Financial Data Quality Managem...,13003.50,USD,US01-K - US012774---PL - US01 - US76--,SE US (US01),NaN,BAM,Software Licenses Procurement --- It Softw Mai...,USD
39825,8300000003-1,8300000003,1,Issued,Sent via Email,Coupa 6 months 5000 users subscription renewal,125000.00,EUR,FREN-K - 53997-P - SP-AUTO-PG1039-PL - FREN - ...,SEI SAS (FREN),NaN,BEU,Software As A Service (Saas) Subscriptions ---...,EUR
39826,8300000002-1,8300000002,1,Cancelled,Sent via Email,Smoke Test - Dummy PR,16.84,EUR,FREN-K - 53376---PL - FREN - K323,SEI SAS (FREN),NaN,BEU,Computer Peripherals / Photocopiers --- Office...,EUR

In [78]:
#Upload in Postgres to NEW order line table

join_tables.to_sql(name='order_line', con=engine, if_exists='append', index=False)

## Step 5: After creation of SQL database and importing data, connect to local db

In [81]:
pd.read_sql_query('select * from order_line', con=engine).head()

,po_key,po_number,line,order_status,transmission_method,item,line_total,currency,account,chart_of_accounts,contract_number,erp,item_classification,accounting_total_currency
0,8000016091-1,8000016091,1,Issued,Sent via Email,MUVIT SUPPORT UNIVERSEL NOIR ROTATIF GRI,5.49,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
1,8000016091-2,8000016091,2,Issued,Sent via Email,Targus DrifterTrek with USB Power Pass-T,53.30,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
2,8000016091-3,8000016091,3,Issued,Sent via Email,FRAIS DE PORT,8.00,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
3,8000016090-1,8000016090,1,Issued,Sent via Email,(ST)Stylo bille Bic 4 couleurs 3 + 1 HB - poin...,2.84,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR
4,8000016090-2,8000016090,2,Issued,Sent via Email,(ST)Pile bouton lithium Energizer CR2025 - pac...,5.39,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR

In [82]:
pd.read_sql_query('select po_number from order_line', con=engine).count()

po_number    39827
dtype: int64

In [113]:
pd.read_sql_query('select * from order_line WHERE line_total < 10 ', con=engine).head()

,po_key,po_number,line,order_status,transmission_method,item,line_total,currency,account,chart_of_accounts,contract_number,erp,item_classification,accounting_total_currency
0,8000016091-1,8000016091,1,Issued,Sent via Email,MUVIT SUPPORT UNIVERSEL NOIR ROTATIF GRI,5.49,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
1,8000016091-3,8000016091,3,Issued,Sent via Email,FRAIS DE PORT,8.00,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10058250.0,BEU,Computer Peripherals / Photocopiers --- Office...,EUR
2,8000016090-1,8000016090,1,Issued,Sent via Email,(ST)Stylo bille Bic 4 couleurs 3 + 1 HB - poin...,2.84,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR
3,8000016090-2,8000016090,2,Issued,Sent via Email,(ST)Pile bouton lithium Energizer CR2025 - pac...,5.39,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Supplies --- Office Supplies (Incl Copy...,EUR
4,8000016090-3,8000016090,3,Issued,Sent via Email,(ST)Cadenas Pavo en laiton - fermeture à clé,6.86,EUR,FR02-K - FR026544---PL - FR02 - FR65--,SE France (FR02),10235602.0,BEU,Office Furniture --- Office Furniture (27A2),EUR